/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.petuska.dekorator.plugin

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.gradle.testfixtures.ProjectBuilder

/** A simple unit test for the 'dekorator' plugin. */
class DekoratorPluginTest {
  @Test
  fun `plugin registers task`() {
    val project = ProjectBuilder.builder().build()
    project.plugins.apply("dev.petuska.dekorator")

    assertNotNull(project.extensions.findByName("dekorator"))
  }
}
